runtime: python
env: flex

runtime_config:
  python_version: 3

handlers:
  - url: .*
    script: fasttext_restapi.app

resources:
  memory_gb: 4

entrypoint: gunicorn -t 0 -b :$PORT fasttext_restapi:app
